# Generated by Django 5.0.6 on 2024-06-29 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_accesorios_bicicleta_cliente_rental_delete_curso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesorios',
            options={'verbose_name': 'Accesorios', 'verbose_name_plural': 'Accesorios'},
        ),
    ]
