# Generated by Django 5.0.6 on 2024-06-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_alter_accesorios_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesorios',
            options={'ordering': ['tipo', 'marca'], 'verbose_name': 'Accesorios', 'verbose_name_plural': 'Accesorios'},
        ),
        migrations.RemoveField(
            model_name='bicicleta',
            name='disponibilidad',
        ),
    ]
