# Generated by Django 5.0.6 on 2024-07-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_alter_accesorios_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['identificacion']},
        ),
    ]
