# Generated by Django 5.0.6 on 2024-07-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='equipos',
            field=models.CharField(default='Equipos y Accesorios', max_length=30),
            preserve_default=False,
        ),
    ]
