# Generated by Django 5.0.6 on 2024-07-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_rental_equipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendero', models.CharField(max_length=30)),
                ('dificultad', models.CharField(max_length=30)),
                ('distancia', models.CharField(max_length=30)),
            ],
        ),
    ]
