# Generated by Django 5.0.6 on 2024-07-13 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_alter_cliente_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='foto',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='bicicletas'),
            preserve_default=False,
        ),
    ]
