# Generated by Django 5.0.6 on 2024-07-14 22:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0012_bicicleta_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicicleta',
            name='foto',
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='bicicletas', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
