# Generated by Django 5.0.6 on 2024-07-16 23:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0013_remove_bicicleta_foto_bicicleta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='accesorios',
            field=models.CharField(default="text", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='bicicleta',
            field=models.CharField(default="text", max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cant_dias',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
