# Generated by Django 5.0.6 on 2024-07-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_cliente_accesorios_cliente_bicicleta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cant_dias',
            field=models.CharField(max_length=2),
        ),
    ]
