# Generated by Django 5.0.6 on 2024-07-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0019_alter_cliente_options_rename_bicicleta_cliente_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
