# Generated by Django 5.0.6 on 2024-07-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0020_cliente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
